Controllers films users
evxq/java-filmorate pull request #3
Opened 2023-02-14 22:55 UTC by evxq

2023-02-15 17:12 UTC, TomattmanYandex requested changes
Привет, хорошая работа но есть непонятные моменты и места которые надо поправить

2023-02-15 17:12 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private ValidationException filmValidation(Film film) {
обычно с ошибками работают по другому, не возвращают их из метода, а просто пробрасывают, стоит сделать тип возвращаемого значения void и в случае ошибки валидации просто генерировать ValidationException
а еще лучше переименовать метод, обычно в начале имени метода действие какое он будет делать, тут валидировать - лучшее имя будет validate или validateFilm

2023-02-15 17:12 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private ValidationException filmValidation(Film film) {
С изменением это логики также надо будет поменять немного логику методов выше

2023-02-15 17:12 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
те же комменты что и к классу выше

2023-02-15 17:12 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
лучше использовать обертку вместо примитива

2023-02-15 17:12 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            for (byte b : user.getEmail().getBytes()) {
что за непонятная логика?

2023-02-15 17:12 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
снова лучше использовать обертку вместо примитива

2023-02-16 19:14 UTC, evxq commented
Исправил замечания
Кстати, как уведомить проверяющего, что внесены изменения? 
Достаточно в этом диалоге оставить коммент?

2023-02-17 13:17 UTC, TomattmanYandex approved these changes
Принято

2023-02-17 16:45 UTC, merged